src/app/app-routing.module.ts, src/app/profile/pages/profile.component.html, src/app/profile/profile.module.ts, src/app/timeline/pages/timeline.component.css, src/app/timeline/pages/timeline.component.html
Adding static components to visual how the main page will look like
=> added static profile card

server/routes/login_register.js, server/server.js
I am in the process of fixing the API for register and login. Once i finish working on it, I will work on the encryption and Forgot password Process.
=> Working process on Login-Register API

server/routes/login_register.js
Now, The register API is working correctly. To further improve this method, it is necessary to check if a user already has an account with us. 
Furthermore, It is necessary to execute several test cases to improve the functionality of this API.
Also, I will create a basic case for login and we can improve and add more specific cases after executing some test cases.
=> Register Api Working

server/routes/login_register.js
I have implemented the Login API and took some cases into consideration. However, I haven't tested it yet.
=> Implemented the Login API

server/routes/login_register.js
In our case, the email is unique. Therefore, the method will verify if the new user is using an email that already existing in our database. If it does exist, then it won't let him register and will ask him to use a different email. Moreover, the method will verify that the inserted info (username, password and email) aren't empty.
=> modified the Register API

package-lock.json, server/routes/login_register.js
I had some problems with my branch. this is just to merge it with the master branch
=> I just added a comment

server/routes/login_register.js, src/app/login/login.component.html, src/app/register/pages/register.component.ts
For logging,  the user can login using his username instead of email. Therefore, the username and the email are unique.
=> Changing the email to username for logining

src/app/register/pages/register.component.html
As you can see Robert, I have made very small changes but helped to fix the bugs regarding:
- sending the value 1 or 2 to the database for the gender.
- You forgot to call the method RegisterUser when clicking on  Sign up.
=> Fixed Register Frontend bug

server/routes/login_register.js
I just fixed the data sent to the database when a user is trying to register.
=> Small adjustement in the login_register.js file

server/routes/login_register.js, server/routes/timeline.js, server/server.js
in process to create the backend to retrieve wits from the backend and show them at the frontend
=> working on the timeline backend

server/routes/login_register.js, server/routes/timeline.js, src/app/timeline/pages/timeline.component.ts, src/app/timeline/services/timeline.service.ts
For the backend of the timeline is working correctly to retrieve the wits needed and push them to the frontend. Also,the connection between the frontend and the backend is implemented correctly now. @CarenRizk will be taking care of showing them on the frontend from the most resent one to the last oldest one.
=> the backend is connected to the frontend for showing the wits

server/routes/login_register.js, src/app/app.module.ts, src/app/login/login.component.html, src/app/login/login.component.ts, src/app/login/login.module.ts
Validation form for the login page has been updated. Only the field required is handled. Communication with the backend concerning the validity of the username and/or password is not yet fully implemented.
=> High Level Login Validation Form 

server/routes/login_register.js, server/routes/timeline.js, src/app/login/login.component.html, src/app/login/login.component.ts, src/app/register/pages/register.component.html
- I fixed the bug regarding of telling the user if they tried to login with a wrong email or password.
- I fixed a small bug in the register where the registration request was been sent twice every time.
- I created the back end in case if the user wanted to see who liked a specific wit.
=> Fixing login bug and sending the list of likes

src/app/timeline/pages/timeline.component.html, src/app/timeline/pages/timeline.component.ts
The wits field will be added by karen.
=> TimelineProfile is working

src/app/app.module.ts, src/app/timeline/dialog/dialog/dialog.component.html, src/app/timeline/dialog/dialog/dialog.component.spec.ts, src/app/timeline/dialog/dialog/dialog.component.ts, src/app/timeline/pages/timeline.component.html, src/app/timeline/pages/timeline.component.ts, src/app/timeline/services/timeline.service.ts, src/app/timeline/timeline.module.ts
I  am in the process for implementing the Open Dialog for displaying the users's names who liked a wit.
=> Implementing the open Dialog for likes' list #88

server/routes/timeline.js, src/app/app-routing.module.ts, src/app/app.module.ts, src/app/timeline/dialog/dialog/dialog.component.html, src/app/timeline/dialog/dialog/dialog.component.ts, src/app/timeline/pages/timeline.component.html, src/app/timeline/pages/timeline.component.ts, src/app/timeline/services/timeline.service.ts
We will get a list of likes on openDialog page where the names of the people who liked the post will appear. Furthermore, The user can not like his own wits is implemented.
=> Implemented Open Dialog for Like list #88 and not like oneself wit #111

.travis.yml
Adding .travis.yml file and allowing the Travis CI access to this repo. 
Issue #42
=> Setting up Travis CI with travis.yml file

src/app/login/login.component.ts, src/app/login/login.module.ts
If the user enters an invalid username, it will trigger an alert. If the user enters an invalid password, it will trigger a different alert. Solves issue #118
=> Invalid username and invalid password alerts for login page 

src/app/profile/pages/profile.component.css, src/app/profile/pages/profile.component.html
added the profile picture and user info for the profile #71
=> Profile frontend

package-lock.json, package.json, src/app/timeline/pages/timeline.component.html, src/app/timeline/pages/timeline.component.ts
buttons were showing under each other for each wit, changed it to be next to each other
=> timeline buttons styling

src/app/app.component.ts, src/app/app.module.ts, src/app/interceptor/token-interceptor.service.ts, src/app/shared/services/auth.service.ts
Hi Haboub #Haboub <3 ! 
After some time of checking all possibilities for handling token and HTTP responses/requests, I found a straightforward way. I added a small file called token-interceptor.service.ts and added some tweaks in the auth.service.ts as well as the app.module.ts. I tested it also upon login and I'm able to retrieve the token from one of the multiple events. I will still have to understand a bit further everything related to http/token responses/requests but I know that we could do very powerful things. i.e for login/logout authentification for instance. I attached a pic to show you exactly how I tested it. 
We should meet before talking about how we could implement it in our project. 
Fixes #105
=> Token interface implementation.

package-lock.json, server/routes/followUser.js, server/routes/login_register.js, server/server.js, src/app/timeline/pages/timeline.component.ts
Merging working version of follow user backend with master
=> Follow user Backend

src/app/profile/pages/profile.component.html, src/app/profile/pages/profile.component.ts
Updated profile front-end with data from DB.
=> Fetching user info from back-end into profile page. Issue #71

server/routes/profile.js, src/app/profile/services/profile.service.ts
http post request for deleting wits from the database. The event of deleting will be possible from the profile page.
=> Backend for deleting wits from the profile page

server/routes/profile.js, src/app/app.module.ts, src/app/profile/dialogprofile/dialogprofile.component.html, src/app/profile/dialogprofile/dialogprofile.component.spec.ts, src/app/profile/dialogprofile/dialogprofile.component.ts, src/app/profile/pages/profile.component.html, src/app/profile/pages/profile.component.ts, src/app/profile/profile.module.ts, src/app/profile/services/profile.service.ts
This pull request consists of the commits that solves the issue #102 
This issue was to display the wits of the user on his profile.
=> Display the wits posted by user on their profile Solves issue #102

server/routes/timeline.js
Get replies for posts implemented (issue number #141 )
=> Timeline show posts

server/routes/timeline.js
delete a comment is done (issue #152 )
=> deleting a specific reply backend implemented

.travis.yml, package-lock.json, package.json, server/routes/followUsers.test.js, server/routes/timeline.js, server/server.js, src/app/timeline/dialog-replies/dialog-replies.component.ts, src/app/timeline/pages/timeline.component.ts, src/app/timeline/services/timeline.service.ts, tests.js
Hey Caren, I have fixed some stuff. Implemented the frontend for liking/unliking. However, I am having the problem of refreshing.
=> Implementation of the liking/unliking of a reply #118

server/routes/followUser.js
The follow/unfollow in the backend is fully implemented. 
Solved issue #100 
and sub user Story #108  [for the backend only]
=> Consolidation of follow/Unfollow feature

package-lock.json, server/routes/followUsers.test.js
Following and unfollow have been tested.
You cannot follow yourself.
related to issue #153
=> Three test cases regarding the follow feature

src/app/profile/pages/profile.component.html
=> added user tab on profile

src/app/profile/dialog-following/dialog-following.component.spec.ts
this is what you meant i believe ?
=> testing TravisCI after a failure

server/routes/followUsers.test.js
=> test for liking a wit of someone you are not following and unliking a wit

package-lock.json, server/routes/timeline.js
There was a problem where the posts were  n't showing up on the timeline.
=> fixed a bug regarding the posting #34

server/routes/followUser.js, src/app/search-engine/pages/search-engine.component.css, src/app/search-engine/pages/search-engine.component.html, src/app/search-engine/pages/search-engine.component.ts, src/app/search-engine/services/follow.service.spec.ts, src/app/search-engine/services/follow.service.ts, src/app/timeline/services/timeline.service.ts
Follow button in search list implemented regarding issue #199
=> follow button implemented #199

server/routes/followUser.js, src/app/search-engine/pages/search-engine.component.html, src/app/search-engine/pages/search-engine.component.ts
So, now, the user can't follow themselves when they search themselves. Also, I have fixed the bug with the dynamic button. They are working perfectly now.
=> #108 completed and fixed the bug for following

server/routes/login_register.js, src/app/app.module.ts, src/app/profile/editprofile-dialog/editprofile-dialog.component.css, src/app/profile/editprofile-dialog/editprofile-dialog.component.html, src/app/profile/editprofile-dialog/editprofile-dialog.component.spec.ts, src/app/profile/editprofile-dialog/editprofile-dialog.component.ts, src/app/profile/pages/profile.component.html, src/app/profile/pages/profile.component.ts, src/app/profile/profile.module.ts, src/app/profile/services/profile.service.ts
Now the backend is working correctly to change the username. However you still need to figure out how to change the other info.
=> Fixing the backend bug for editing the user's info #158

database/mySQL.sql, server/routes/followUser.js, server/routes/login_register.js
I added other stuff regarding the bug for editing #158
=> new updates regarding the edit bug

src/app/search-engine/pages/search-engine.component.html, src/app/search-engine/pages/search-engine.component.ts, src/app/user-profile/pages/user-profile.component.ts
=> Fixed goToProfileURL

src/app/profile/pages/profile.component.ts, src/app/search-engine/pages/search-engine.component.html, src/app/user-profile/pages/user-profile.component.html, src/app/user-profile/pages/user-profile.component.ts
Fixed following a user + some red in the logs
=> fixed follow button in search-engine

server/routes/followUser.js, src/app/profile/pages/profile.component.html, src/app/user-profile/pages/user-profile.component.css, src/app/user-profile/pages/user-profile.component.html, src/app/user-profile/pages/user-profile.component.ts
=> Dynamic follow button on user profile

server/functions/methodsForLoginAndRegister.js, server/routes/login_register.js, server/routes/searchEngine.js, server/routes/timeline.js, server/server.js
I refacotored the two files: SearchEngine and login/register
=> Refactoring backend 

src/app/profile/dialogs/dialogprofile/dialogprofile.component.ts, src/app/profile/dialogs/editprofile-dialog/editprofile-dialog.component.ts, src/app/profile/pages/profile.component.html, src/app/profile/pages/profile.component.ts, src/app/profile/pages/user-followers/user-followers.component.css, src/app/profile/pages/user-followers/user-followers.component.html, src/app/profile/pages/user-followers/user-followers.component.spec.ts, src/app/profile/pages/user-followers/user-followers.component.ts, src/app/profile/pages/user-following/user-following.component.html, src/app/profile/pages/user-following/user-following.component.spec.ts, src/app/profile/pages/user-following/user-following.component.ts, src/app/profile/pages/user-info-card/user-info-card.component.css, src/app/profile/pages/user-info-card/user-info-card.component.html, src/app/profile/pages/user-info-card/user-info-card.component.spec.ts, src/app/profile/pages/user-info-card/user-info-card.component.ts, src/app/profile/pages/user-likes/user-likes.component.css, src/app/profile/pages/user-likes/user-likes.component.html, src/app/profile/pages/user-likes/user-likes.component.spec.ts, src/app/profile/pages/user-likes/user-likes.component.ts, src/app/profile/pages/user-wits/user-wits.component.css, src/app/profile/pages/user-wits/user-wits.component.html, src/app/profile/pages/user-wits/user-wits.component.spec.ts, src/app/profile/pages/user-wits/user-wits.component.ts, src/app/profile/profile.module.ts, src/app/timeline/dialogs/dialog-replies/dialog-replies.component.html, src/app/timeline/dialogs/dialog-replies/dialog-replies.component.ts
Profile refactoring almost done, waiting for connection with back-end to finish to finalize profile refactoring.
=> Last sprint changes

server/routes/login_register.js
Fixed the bug for the register XD missing space :)
=> fixed small bug register backend

server/routes/login_register.js
I found a way to handle the profile pic but I can't succeed to make it work.
If someone can take a look at it between you two. Hampic and me will work on it tomorrow evening. 
File upload with express & multer.
Here's the link.
https://github.com/bradtraversy/nodeuploads/blob/master/app.js
=> Profile picture [incompleted implementation]

server/routes/followUser.js, server/routes/searchEngine.js, server/routes/userProfile.js, src/app/profile/services/profile.service.ts, src/app/search-engine/pages/search-engine.component.ts, src/app/timeline/services/timeline.service.ts, src/app/user-profile/pages/user-likes/user-likes.component.ts, src/app/user-profile/pages/user-profile.component.ts, src/app/user-profile/pages/user-wits/user-wits.component.ts, src/app/user-profile/services/user-profile-service.service.ts
Refactoring the connection the profile backend.
=> Refacotring

src/app/profile/dialogs/dialog-following/dialog-following.component.html, src/app/profile/dialogs/dialogprofile/dialogprofile.component.html, src/app/profile/pages/profile.component.html, src/app/profile/pages/user-following/user-following.component.ts, src/app/profile/pages/user-likes/user-likes.component.ts, src/app/user-profile/pages/user-likes/user-likes.component.ts, src/app/user-profile/pages/user-profile.component.html
I have fixed a bug with the likes tab in the profile. it is still not dynamic.
=> refactoring profile-backend connection #216

src/app/profile/dialogs/dialog-following/dialog-following.component.ts, src/app/profile/dialogs/dialogprofile/dialogprofile.component.ts, src/app/profile/pages/profile.component.html, src/app/profile/pages/profile.component.ts, src/app/profile/pages/user-followers/user-followers.component.ts, src/app/profile/pages/user-following/user-following.component.ts, src/app/profile/pages/user-likes/user-likes.component.ts, src/app/profile/services/profile.service.ts, src/app/timeline/dialogs/dialog-replies/dialog-replies.component.ts, src/app/user-profile/pages/user-likes/user-likes.component.html, src/app/user-profile/pages/user-likes/user-likes.component.ts, src/app/user-profile/pages/user-wits/user-wits.component.css, src/app/user-profile/pages/user-wits/user-wits.component.html, src/app/user-profile/pages/user-wits/user-wits.component.ts
We have some small bugs regarding the wits on the profile. As well as we have refactored the code a bit more.
=> Refactored with fixing small bugs profile #216

src/app/profile/dialogs/dialog-following/dialog-following.component.ts, src/app/profile/dialogs/dialogprofile/dialogprofile.component.ts, src/app/profile/pages/user-likes/user-likes.component.ts, src/app/timeline/services/timeline.service.ts, src/app/user-profile/pages/user-followers/user-followers.component.ts, src/app/user-profile/pages/user-following/user-following.component.ts, src/app/user-profile/pages/user-likes/user-likes.component.css, src/app/user-profile/pages/user-likes/user-likes.component.html, src/app/user-profile/pages/user-likes/user-likes.component.ts, src/app/user-profile/pages/user-profile.component.css, src/app/user-profile/pages/user-profile.component.html, src/app/user-profile/services/user-profile-service.service.ts
Fixing bugs in user-profile  with refactoring the code #215
=> Refactoring

server/routes/follow/followUser.js, server/routes/postWit_postReply/edit.js, src/app/profile/services/profile.service.ts, src/app/search-engine/pages/search-engine.component.html, src/app/search-engine/pages/search-engine.component.ts, src/app/search-engine/services/search-engine.service.ts, src/app/user-profile/pages/user-info/user-info.component.html, src/app/user-profile/pages/user-info/user-info.component.ts, src/app/user-profile/pages/user-likes/user-likes.component.ts
I have added one more useful function for the backend of editing a reply --> the method will help u to retrieve the content of a reply and thus the user can work on it #149 . 
Furthermore, I have fixed some bugs in the serachEngine which were introduced after refactoring the code #215. 
Finally, I have created the connection to the frontend for editing 
the functions are:
-getReplyContent
-editReplyContent
These both methods are in the Profile service file
=> Updating the backend for edit a reply

src/app/profile/services/profile.service.ts, src/app/timeline/services/timeline.service.ts
Correcting the location of reply wit links
=> Adding local links in correct files

server/server.js, src/app/timeline/dialogs/dialog-replies/dialog-replies.component.html, src/app/timeline/dialogs/dialog-replies/dialog-replies.component.ts
I have started implementing the frontend for the edit button. #147
=> Adding the edit button and backend function

database/mySQL.sql, server/routes/main_pages/profile.js, server/routes/main_pages/searchEngine.js, server/routes/main_pages/timeline.js, server/routes/main_pages/userProfile.js, src/app/user-profile/pages/user-likes/user-likes.component.html, src/app/user-profile/pages/user-likes/user-likes.component.ts
I have added a new column in the database which will show if the user Logged In has liked one of the posts that was liked by a user that was search by the serachEngine. 
I fixed the backend a bit more #215
=> Editing the likedWits backend #215

server/routes/follow/followUser.js, server/routes/follow/followerList.js, server/routes/follow/followingList.js, server/routes/like/likeCheck.js, server/routes/like/likeList.js, server/routes/like/likeReply.js, server/routes/like/likeWit.js
I fxed the bug, you were having . As a matter of fact, it was a problem that we had while we were refactoring the code. Anyways, it is working correctly now :)
=> enforcing coding style #254

server/routes/main_pages/searchEngine.js
I have implemented to show the list of usernames that are similar to the one been searched #167
=> Implemented #167 to have a list of similar usernames

server/routes/main_pages/profile.js, src/app/profile/dialogs/editprofile-dialog/editprofile-dialog.component.html, src/app/profile/dialogs/editprofile-dialog/editprofile-dialog.component.ts, src/app/profile/dialogs/password-dialog/password-dialog.component.html, src/app/profile/dialogs/password-dialog/password-dialog.component.spec.ts, src/app/profile/dialogs/password-dialog/password-dialog.component.ts, src/app/profile/services/profile.service.ts
This implementation is the window that will let the user reset his password. 
The user will only be able to reset his password, if and only if he/she knows his old password.
This form of security enforcement prevents any other people that may have landed on the page to change the password of the user, without his/her consent.
Here is a screenshot!
Solves the issue #261
Solve the issues #262
Fix to the issue #256
=> Implementation of reset password 

src/app/profile/pages/user-info-card/user-info-card.component.html
update the user info card front-end
Reference to issue #215
=> Update the user info-card front end

server/routes/follow/followerList.js, server/routes/follow/followingList.js, server/routes/like/likeCheck.js, server/routes/like/likeReply.js, server/routes/like/likeWit.js, server/routes/main_pages/fileUpload.js, server/routes/main_pages/login_register.js, server/routes/main_pages/profile.js, server/routes/main_pages/searchEngine.js, server/routes/main_pages/timeline.js, server/routes/main_pages/userProfile.js, server/routes/postWit_postReply/delete.js, server/routes/postWit_postReply/edit.js, server/routes/postWit_postReply/post.js, server/routes/postWit_postReply/repliesList.js
I followed the guideline specified for the coding style
I'm just not sure about where i need to add the ';'
#215
=> Refactoring the backend #215 #254

src/app/search-engine/pages/search-engine.component.html, src/app/timeline/pages/list-of-wits/list-of-wits.component.css, src/app/timeline/pages/list-of-wits/list-of-wits.component.html, src/app/toolbar/pages/toolbar.component.html
still need to add it in some places but not sure if it's implemented in the database...more work is still blocked for the front end
=> dynamic user image was missing from someplaces

server/server.js
I followed the same guidelines as the rest of the backend files
=> Modified coding style in server.js

server/routes/main_pages/searchEngine.js, src/app/toolbar/pages/search/search.component.html, src/app/toolbar/pages/search/search.component.ts, src/app/toolbar/pages/search/services/search.service.spec.ts, src/app/toolbar/pages/search/services/search.service.ts
The autocomplete search popdown feature has been implemented. Users are now able to search for users and access a dynamic popdown list of suggested usernames. This is related to issue #167 and user story #165
=> Dynamic search

server/routes/followUsers.test.js, src/app/search-engine/services/search-engine.service.spec.ts
=> Adding some more test cases

server/routes/main_pages/profile.js, src/app/profile/dialogs/editprofile-dialog/editprofile-dialog.component.ts
Refactoring the file profile.js
solving issue #215
=> Code styling for profile.js

src/app/forget/pages/forget.component.ts, src/app/login/login.component.ts, src/app/profile/dialogs/editprofile-dialog/editprofile-dialog.component.ts, src/app/profile/dialogs/password-dialog/password-dialog.component.ts, src/app/profile/pages/user-followers/user-followers.component.ts, src/app/toolbar/pages/search/search.component.html, src/app/toolbar/pages/search/search.component.ts, src/app/toolbar/pages/toolbar.component.ts
had to do some changes that i forgot to take care of during the refactoring
=> last touches for refactoring #215
